# Generated by Django 3.1 on 2020-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=5)),
                ('programme', models.CharField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('Phd', 'Phd')], default='Btech', max_length=5)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
