# Generated by Django 3.1 on 2020-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(max_length=5, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='programme',
            field=models.CharField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('Phd', 'Phd')], default='Btech', max_length=5, verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.PositiveIntegerField(verbose_name='Roll_no'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
