# Generated by Django 3.1 on 2020-08-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_issue', '0002_auto_20200825_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookissuecode',
            options={'permissions': (('can_enter_code_to_issue_book', 'can enter code to issue book'),)},
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='issued_book_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_book', to='books.book'),
        ),
    ]
