# Generated by Django 3.1 on 2020-08-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
        ('book_issue', '0003_auto_20200827_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreturn',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='return_book_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='return_code',
            field=models.CharField(default='asdfgh', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreturn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_book', to='books.book'),
        ),
    ]
