# Generated by Django 3.1 on 2020-08-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_issue', '0007_auto_20200829_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('payed', models.BooleanField(default=False)),
                ('payed_date', models.DateTimeField(blank=True, null=True)),
                ('returned_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_issue.bookreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
